version: '3.8'

services:
  backend:
    build: ./backend
    container_name: chat-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/chatdb
      - JWT_SECRET=some_super_secret_key
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: chat-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo:5.0
    container_name: chat-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: chatdb
